seed: 12345
output_dir: "results/training_data"
output_prefix: "archie_rep_model"
seq_len: 50000
nrep: 10000
inner_batch_size: 100 
total_rep: 1000000
demes: 'ArchIE_3D19.yaml'
demog_id: 'ArchIE_3D19'
ploidy: 2
mut_rate: 1.25e-8
rec_rate: 1e-8
ref_id: 'Ref'
tgt_id: 'Tgt'
src_id: 'Ghost'
nref: 50
ntgt: 50
is_phased: True
polymorphisms: 128
remove_samples_wo_introgression: True
random_restrict: True
no_window: False
stepsize: 16
random_el: 1
only_first: True
return_data: False
create_extras: True
remove_intermediate_data: True
hdf_filename: "introunet_archie_rep.h5"
training_dir: "results/trained_introunet_rep"
seq_len_prediction: 1000000
nrep_prediction: 100
total_rep_prediction: 1000
inner_batch_size_prediction: 10
hdf_filename_prediction: "introunet_archie_rep_prediction.h5"
prediction_dir: "results/inference"
