seed: 12345
output_dir: "results/training_data"
output_prefix: "100k_random_wo"
seq_len: 50000
nrep: 1000
total_rep: 100000

### Config for rule simulating_training_data

demes: 'ArchIE_3D19.yaml'
demog_id: 'ArchIE_3D19'
ploidy: 2
mut_rate: 1.25e-8
rec_rate: 1e-8
ref_id: 'Ref'
tgt_id: 'Tgt'
src_id: 'Ghost'
nref: 50
ntgt: 50
is_phased: True

### Config for rule create_h5_files

polymorphisms: 128
remove_samples_wo_introgression: True
random_restrict: True
no_window: False
stepsize: 16
random_el: 1
only_first: True
return_data: False
create_extras: True
remove_intermediate_data: True
batch_sizes:
    - 32
    - 64
    - 128
