seed: 12345
output_dir: "results/training_data"
output_prefix: "archie_rep_model"
seq_len: 50000
nrep: 100
total_rep: 100000
demes: 'ArchIE_3D19.yaml'
demog_id: 'ArchIE_3D19'
ploidy: 2
mut_rate: 1.25e-8
rec_rate: 1e-8
ref_id: 'Ref'
tgt_id: 'Tgt'
src_id: 'Ghost'
nref: 50
ntgt: 50
is_phased: True
polymorphisms: 128
remove_samples_wo_introgression: True
random_restrict: True
no_window: False
stepsize: 16
random_el: 1
only_first: True
return_data: False
create_extras: True
remove_intermediate_data: True
hdf_filename: "1000k_random_wo.h5"
